### ISSUE TITLE
Using Anglesharp with AngularJS web page

### ISSUE THREAD

**Issue by danhastings** [AngleSharp/AngleSharp.Js#44]
I am trying to get this to work with a web page that is using angular JS. I have the following config.

```
            this.Requester = new HttpRequester();
            this.Requester.Headers["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36";

            this.Config = Configuration.Default.WithDefaultLoader(requesters: new[] { this.Requester }).WithJavaScript();
```

When i inspect the innerhtml of the body while debugging in Visual Studio, i can see that it hasnt even detected javascript. 

```
<p>
<strong>JavaScript seems to be disabled in your browser.</strong><br/>
You must have JavaScript enabled in your browser to utilize the functionality of this website. </p>
```

Does this library support angularJS websites, or have i set the config wrong?

**Comment by FlorianRappl** [comment]
This library does not care about Angular or any other particular JS library - it only cares about JavaScript. 

From the snippet above the config seems alright. "Has not even detected JavaScript" is a whacky statement. This content must be available in the pure website, i.e., if some script was run successfully it would be overwritten or deleted. Thus it is safe to assume that the script was not run successfully. While this could be a timing issue (I don't know when you inspect the content) I think that it is more likely that the website's JS code or Angular itself is requiring too many features that are not available in AngleSharp or exposed via the scripting layer. In order to find out more debugging would be necessary.
